### PR TITLE
added download function and cleaned up html

### PR DESCRIPTION
**Pull request by zackrylangford**
I hope you don't mind I was playing around with your code for whisper :) 

I am starting to learn more about it as well and was looking at what others are doing. I wanted to help contribute to a project that is just getting started, as I am just getting started as well. Here is what I changed (more detailed explanations can be provided if you want them!)

1. Refactor make_srt_subtitles function to accept list of segments (This refactoring simplifies the function's logic and improves its compatibility with the transcription results from the Whisper ASR API.)
2. Add a new /download/ endpoint for downloading subtitle files automatically to the user's browser
3.  Moved the JavaScript to the static folder to keep the HTML cleaner
4. Updated the HTML to use some simple bootstrap classes to clean up the page

If you are interested in collaborating, I have experience in developing Django Web Applications and can create a web based interface for this to use in any website or web applications. 

No worries if you don't like any of the changes, looking forward to seeing where this app can go!

### CODE REVIEW

**Comment by Kabanosk** [comment]
Hi! First, thank you very much for your contribution to this project. I tested your code and I think that it looks better but the timestamps doesn't work on my computer - I printed the timestamps variable in `/download/` endpoint and it is `None` no matter if I tick the checkbox or not. 

I like the changes you made and I will merge them when the timestamps work. If you don't have time I will have some time at Wednesday, so I can try to fix them.

I will be very happy to collaborate with you :D

**Comment by zackrylangford** [comment]
Cool, I will take a look and see what's happening with the time stamps. Sounds good 👍🏼

**Review by zackrylangford — COMMENTED** [review]
Changes in add_audio:

Replaced the separate extraction of form inputs with FastAPI's Form() functionality, which directly assigns the input values to the corresponding function parameters.
Removed the unnecessary asyncio.run() call and replaced the try-except block with an optional default value for the timestamps parameter.
Changed the condition to check for timestamps to a direct string comparison (timestamps == "True").
Changes in download_subtitle:

Replaced the optional timestamps parameter with a default value of "False" using FastAPI's Form() functionality.
Updated the condition for creating a timestamps_text to a direct string comparison (timestamps == "True").

**Comment by zackrylangford** [comment]
Let me know if it still causes issues. I ran it on a different machine this time to make sure. Hopefully it works on your end!

**Comment by Kabanosk** [comment]
This is working now! Thanks for your contribution! If you have other ideas to improve this project, I'll be happy to help you with them!

**Comment by zackrylangford** [comment]
Great! Thank you! 

I don't have anything right now as far as ideas for it, I'm just getting started with learning about the Whisper API. Not sure how to implement it with what I'm currently working on, but am looking for projects like yours to build with and get a feel for what it can do. 

Do you have plans to develop this project further?

**Comment by Kabanosk** [comment]
Yes, I have plan to develop it, but I need to think what I can add to this. Thank you once again for your contribution!

**Pull request merged**
